-- CREATE TABLE BLOGS

CREATE TABLE posts(
   id INTEGER PRIMARY KEY AUTO_INCREMENT,
   title VARCHAR(200) NOT NULL,
   description VARCHAR(1500),
   author VARCHAR(200) NOT NULL,
   image_url VARCHAR(255),
   done BOOLEAN NOT NULL DEFAULT 1,
   createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)
